interface AdminRoute {
  path: string,
  permission: string,
  method: string
}
const Routes = [
  // admin user routes
  {
    path:"/getrolebyid",
    role:"Admin",
    permission:"role.read",
    method:"get"
  },
  {
    path:"/profile",
    role:"Admin",
    permission:"user.profile"
  },
  {
    path:"/logout",
    role:"Admin",
    permission:"user.logout"
  },
  {
    path:"/profile-update",
    role:"Admin",
    permission:"profile.update"
  },
  {
    path:"/user-enable-disable",
    role:"Admin",
    permission:"user.update"
  },
  {
    path:"/userrole",
    role:"Admin",
    permission:"user.role"
  },
  {
    path:"/recentusers",
    role:"Admin",
    permission:"users.read"
  },
  {
    path:"/totalusers",
    role:"Admin",
    permission:"users.read"
  },
  {
    path:"/activeusers",
    role:"Admin",
    permission:"users.read"
  },
  {
    path:"/inactiveusers",
    role:"Admin",
    permission:"users.read"
  },
  {
    path:"/users",
    role:"Admin",
    permission:"users.read"
  },
  {
    path:"/user",
    role:"Admin",
    permission:"user.read"
  },
  // Admin role routes
  {
    path:"/createrole",
    role:"Admin",
    permission:"role.create"
  },
  {
    path:"/getallrole",
    role:"Admin",
    permission:"roles.read"
  },
  {
    path:"/getrolebyname",
    role:"Admin",
    permission:"role.read"
  },
  {
    path:"/updaterole",
    role:"Admin",
    permission:"role.update"
  },
  {
    path:"/deleterole",
    role:"Admin",
    permission:"role.delete"
  },
  {
    path:"/getrolebyid",
    role:"Admin",
    permission:"role.read"
  },
  // user routes
  {
    path:"/profile",
    role:"User",
    permission:"user.profile"
  },
  {
    path:"/logout",
    role:"User",
    permission:"user.logout"
  },
  {
    path:"/profile-update",
    role:"User",
    permission:"profile.update"
  },
  // timesheet routes for admin
  {
    path:"/aggregation/v1/timesheet/admin/get",
    role:"Admin",
    permission:"timesheets.read",
  },
  {
    path:"/aggregation/v1/timesheet/admin",
    role:"Admin",
    permission:"timesheet.create"
  },
  {
    path:"/aggregation/v1/timesheet/admin/timesheetbyId",
    role:"Admin",
    permission:"timesheet.read"
  },
  {
    path:"/aggregation/v1/timesheet/admin/temp",
    role:"Admin",
    permission:"timesheet.delete"
  },
  {
    path:"/aggregation/v1/timesheet/admin/del",
    role:"Admin",
    permission:"timesheet.delete",
  },
  {
    path:"/aggregation/v1/timesheet/admin/get/count-employe-today",
    role:"Admin",
    permission:"user.read",
  },
  {
    path:"/aggregation/v1/timesheet/admin/export",
    role:"Admin",
    permission:"users.read",
  },
  {
    path:"/aggregation/v1/timesheet/admin/total-timesheet-hours",
    role:"Admin",
    permission:"timesheets.read"
  },
  {
    path:"/aggregation/v1/timesheet/admin/timesheet-miss-thirty-days",
    role:"Admin",
    permission:"users.read"
  },
  {
    path:"/aggregation/v1/timesheet/admin/timesheet-hours-by-project",
    role:"Admin",
    permission:"project.hours"
  },
  {
    path:"/aggregation/v1/timesheet/admin/incorrect-timesheet",
    role:"Admin",
    permission:"timesheets.read"
  },
  // user timesheet routes
  {
    path:"/aggregation/v1/timesheet",
    role:"User",
    permission:"timesheet.create"
  },
  {
    path:"/aggregation/v1/timesheet/update",
    role:"User",
    permission:"timesheet.update"
  },
  {
    path:"/aggregation/v1/timesheet/get",
    role:"User",
    permission:"timesheet.read"
  },
  {
    path:"/aggregation/v1/timesheet/timesheetbyId",
    role:"User",
    permission:"timesheet.read"
  },
  {
    path:"/aggregation/v1/timesheet/latest",
    role:"User",
    permission:"timesheet.read"
  },
  {
    path:"/aggregation/v1/timesheet/incorrect-timesheet",
    role:"User",
    permission:"timesheet.read"
  },
  // user project routes
  {
    path:"/aggregation/v1/project/get",
    role:"User",
    permission:"projects.read"
  },
  {
    path:"/aggregation/v1/project",
    role:"User",
    permission:"project.read"
  },
  // admin project routes
  {
    path:"/aggregation/v1/project/admin",
    role:"Admin",
    permission:"project.create"
  },
  {
    path:"/aggregation/v1/project/admin/del",
    role:"Admin",
    permission:"project.delete"
  },
  {
    path:"/aggregation/v1/project/admin/temp",
    role:"Admin",
    permission:"project.delete"
  },
  {
    path:"/aggregation/v1/project/admin/get",
    role:"Admin",
    permission:"projects.read"
  },
  {
    path:"/aggregation/v1/project/admin/getById",
    role:"Admin",
    permission:"project.read"
  },
  {
    path:"/aggregation/v1/project/admin/update",
    role:"Admin",
    permission:"project.update"
  },
  {
    path:"media/v2/uploads",
    role:"User",
    permission:"media.upload"
  }
]
export default Routes;